"""
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
"""

from .SeasideHillDarkRegions import *
from .SeasideHillDarkConnections import *
from .SeasideHillDarkTripleSprings import *
from .SeasideHillDarkRings import *
from .SeasideHillDarkHintRings import *
from .SeasideHillDarkItemBoxes import *
from .SeasideHillDarkItemBalloons import *
from .SeasideHillDarkEggFlappers import *
from .SeasideHillDarkEggPawns import *

regions: list[SonicHeroesRegionData] = REGIONS
connections: list[SonicHeroesConnectionData] = CONNECTIONS
triple_springs: list[TripleSpringData] = TRIPLE_SPRINGS
rings: list[RingData] = RINGS
hint_rings: list[HintRingData] = HINT_RINGS
item_boxes: list[ItemBoxData] = ITEM_BOXES
item_balloons: list[ItemBalloonData] = ITEM_BALLOONS
egg_flappers: list[EggFlapper] = EGG_FLAPPERS
egg_pawns: list[EggPawn] = EGG_PAWNS
