
"""
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
"""

from ....constants.char_ability import *
from ....constants.stage import *
from ....constants.stage_objs import *
from ....rule_builder.functions_ability_char import *
from ....rule_builder.functions_enemies import *
from ....rule_builder.functions_stage_obj import *
from ....rule_builder.functions_tricks import *
from ....world_base import SonicHeroesWorldBase

from ....constants.item_balloon_box import *


ITEM_BOXES: list[ItemBoxData] = \
[
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="First Loop 3 x Item Boxes", region_name="Seaside Hill Dark First Loop", item=ItemReward.NoneItemBox, group=-1, id_offset_group=0, id_offset_full=-999999, link_id=0, x=-999999, y=-999999, z=-999999, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="First Loop Left 5 Rings Box", region_name="Seaside Hill Dark First Loop", item=ItemReward.Rings5, group=1, id_offset_group=-999999, id_offset_full=1, link_id=0, x=44.23, y=287.58, z=-5107.67, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="First Loop Center 5 Rings Box", region_name="Seaside Hill Dark First Loop", item=ItemReward.Rings5, group=1, id_offset_group=-999999, id_offset_full=1, link_id=0, x=81.62, y=323.58, z=-5099.388, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="First Loop Right 5 Rings Box", region_name="Seaside Hill Dark First Loop", item=ItemReward.Rings5, group=1, id_offset_group=-999999, id_offset_full=1, link_id=0, x=126.62, y=365.58, z=-5092.609, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Hermit Crab Cliff Below Eggmans Robots Extra life Box", region_name="Seaside Hill Dark Hermit Crab Cliff Below Eggmans Robots", item=ItemReward.ExtraLife, group=0, id_offset_group=3, id_offset_full=1, link_id=0, x=248.877, y=202.6395, z=-6337.48, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Eggmans Robots Top Shield Box In Rock", region_name="Seaside Hill Dark Eggmans Robots Top", item=ItemReward.Shield, group=0, id_offset_group=3, id_offset_full=1, link_id=0, x=-775.99, y=530, z=-6660.06, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX) & can_break_things_rule(team=Team.DARK, stage=Stage.SEASIDE_HILL)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Top Cliff Route With Hermit Crab 10 Rings Box in Iron Container", region_name="Seaside Hill Dark Top Cliff Route With Hermit Crab", item=ItemReward.Rings10, group=0, id_offset_group=3, id_offset_full=1, link_id=0, x=-1769.18, y=619.9, z=-6393.996, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX) & can_break_iron_container_rule(team=Team.DARK, stage=Stage.SEASIDE_HILL)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Corner Cave Loop Center 5 Rings Box", region_name="Seaside Hill Dark Corner Cave", item=ItemReward.Rings5, group=0, id_offset_group=3, id_offset_full=1, link_id=0, x=-4370.176, y=482.0524, z=-7693.988, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Second Cliff Before Big Ruin Beach 10 Rings Box in Rock", region_name="Seaside Hill Dark Second Cliff Before Big Ruin Beach", item=ItemReward.Rings10, group=0, id_offset_group=3, id_offset_full=1, link_id=0, x=589.9285, y=386, z=-16148.27, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX) & can_break_things_rule(team=Team.DARK, stage=Stage.SEASIDE_HILL)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Lower Cliff Before Big Ruin Beach Invincibility Box in Rock", region_name="Seaside Hill Dark Lower Cliff Before Big Ruin Beach", item=ItemReward.Invincibility, group=0, id_offset_group=3, id_offset_full=1, link_id=0, x=454.9761, y=244.7602, z=-16049.88, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX) & can_break_things_rule(team=Team.DARK, stage=Stage.SEASIDE_HILL)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Path After Big Special Ruin Before Volcano Loop 3 x Item Boxes", region_name="Seaside Hill Dark Path After Big Special Ruin Before Volcano Loop", item=ItemReward.NoneItemBox, group=-2, id_offset_group=3, id_offset_full=-999999, link_id=0, x=-999999, y=-999999, z=-999999, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Path After Big Special Ruin Before Volcano Loop Left 5 Rings Box", region_name="Seaside Hill Dark Path After Big Special Ruin Before Volcano Loop", item=ItemReward.Rings5, group=2, id_offset_group=-999999, id_offset_full=2, link_id=0, x=756.006, y=400.8734, z=-26670.38, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Path After Big Special Ruin Before Volcano Loop Center 5 Rings Box", region_name="Seaside Hill Dark Path After Big Special Ruin Before Volcano Loop", item=ItemReward.Rings5, group=2, id_offset_group=-999999, id_offset_full=2, link_id=0, x=804.0079, y=463.8734, z=-26670.47, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Path After Big Special Ruin Before Volcano Loop Right 5 Rings Box", region_name="Seaside Hill Dark Path After Big Special Ruin Before Volcano Loop", item=ItemReward.Rings5, group=2, id_offset_group=-999999, id_offset_full=2, link_id=0, x=856.6043, y=541.8734, z=-26661.36, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX)),
    ItemBoxData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Loop After Second Bobsled Left 5 Rings Box", region_name="Seaside Hill Dark Loop After Second Bobsled", item=ItemReward.Rings5, group=0, id_offset_group=6, id_offset_full=2, link_id=0, x=-540.6484, y=442.7799, z=-40279.72, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.ITEM_BOX))
]