
"""
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
"""

from ....constants.char_ability import *
from ....constants.stage import *
from ....constants.stage_objs import *
from ....rule_builder.functions_ability_char import *
from ....rule_builder.functions_enemies import *
from ....rule_builder.functions_stage_obj import *
from ....rule_builder.functions_tricks import *
from ....world_base import SonicHeroesWorldBase

from ....constants.hint_rings import HintRingData

SeasideHillDarkHintRings: list[HintRingData] = \
[
    HintRingData(team=Team.DARK, stage=Stage.SEASIDE_HILL, region_name="Seaside Hill Dark Beginning Flower Patch", voice_line=27, x=24.45, y=190.0, z=-1632.55, rule=has_stage_obj_rule(stage_obj=StageObj.HINT_RING)),
    HintRingData(team=Team.DARK, stage=Stage.SEASIDE_HILL, region_name="Seaside Hill Dark Eggmans Robots Bottom", voice_line=30, x=-177.01, y=330.0, z=-6675.51, rule=has_stage_obj_rule(stage_obj=StageObj.HINT_RING)),
    HintRingData(team=Team.DARK, stage=Stage.SEASIDE_HILL, region_name="Seaside Hill Dark Eggmans Robots Top", voice_line=414, x=-705.99, y=530.0, z=-6669.76, rule=has_stage_obj_rule(stage_obj=StageObj.HINT_RING)),
    HintRingData(team=Team.DARK, stage=Stage.SEASIDE_HILL, region_name="Seaside Hill Dark Staircase Before Corner Cave Bottom", voice_line=121, x=-2309.88, y=480.0, z=-6401.89, rule=has_stage_obj_rule(stage_obj=StageObj.HINT_RING)),
    HintRingData(team=Team.DARK, stage=Stage.SEASIDE_HILL, region_name="Seaside Hill Dark Ruin Before Corner Cave", voice_line=64, x=-2831.04, y=690.0, z=-6470.78, rule=has_stage_obj_rule(stage_obj=StageObj.HINT_RING)),
    HintRingData(team=Team.DARK, stage=Stage.SEASIDE_HILL, region_name="Seaside Hill Dark First Island", voice_line=78, x=-4490.37, y=21.5, z=-10896.22, rule=has_stage_obj_rule(stage_obj=StageObj.HINT_RING) & (can_combo_height_rule(team=Team.DARK, stage=Stage.SEASIDE_HILL) | can_jump_rule(team=Team.DARK, stage=Stage.SEASIDE_HILL) | can_thundershoot_rule(team=Team.DARK, stage=Stage.SEASIDE_HILL, level=0))),
    HintRingData(team=Team.DARK, stage=Stage.SEASIDE_HILL, region_name="Seaside Hill Dark Ruin Between Big Ruin Beach Islands", voice_line=24, x=1231.38, y=51.09, z=-18541.68, rule=has_stage_obj_rule(stage_obj=StageObj.HINT_RING)),
    HintRingData(team=Team.DARK, stage=Stage.SEASIDE_HILL, region_name="Seaside Hill Dark Big Ruin Beach Island 2", voice_line=2, x=1599.577, y=33.0, z=-19697.19, rule=has_stage_obj_rule(stage_obj=StageObj.HINT_RING))
]