
"""
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
"""

from ....constants.char_ability import *
from ....constants.stage import *
from ....constants.stage_objs import *
from ....rule_builder.functions_ability_char import *
from ....rule_builder.functions_enemies import *
from ....rule_builder.functions_stage_obj import *
from ....rule_builder.functions_tricks import *
from ....world_base import SonicHeroesWorldBase

from ....constants.loc_region import SonicHeroesRegionData


REGIONS: list[SonicHeroesRegionData] = \
[
    SonicHeroesRegionData(region_name="Seaside Hill Dark Start", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark ObjSanity", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark After Beginning Falling Ruins", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Beginning Flower Patch", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Lower Path After Beginning Flower Patch", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Upper Path After Beginning Flower Patch", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Loop", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Eggmans Robots Bottom", obj_checks=4),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Hermit Crab Cliff Below Eggmans Robots", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Eggmans Robots Middle", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Eggmans Robots Top", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Bonus Key 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Small Cliff Above Eggmans Robots", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Top Cliff Route With Hermit Crab", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Bottom Cliff Route", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Bottom", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Bottom Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Middle", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Top", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin Before Corner Cave", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Corner Cave", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island", obj_checks=5),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island Cannon Speed", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island Cannon Power", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island Cannon Flying", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island Top Pillar Right", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island Top Pillar Left", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Ruin Between First and Second Island", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Ruin Between First and Second Island", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Third Ruin Between First and Second Island", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Island", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Island High Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin After Second Island", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin Stairs After Second Island", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Before First Bobsled", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Bobsled", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Bobsled After Block", obj_checks=7),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Bobsled Small Island", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin After First Bobsled", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin After First Bobsled", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Cliff Before Big Ruin Beach", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Cliff Before Big Ruin Beach", obj_checks=4),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Lower Cliff Before Big Ruin Beach", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Ruin Beach", obj_checks=8),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Ruin Beach Cannon Speed", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Ruin Beach Cannon Power", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Ruin Beach Cannon Flying", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Lower Cliffs At Start", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Ruin With Dash Ramp", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Island 1", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Bonus Key 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Island 1 High Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Island 1 Mid Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin Between Big Ruin Beach Islands", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Middle Path Top Corner", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Middle Path Before Blocks", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Middle Path After Blocks", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Top Path 1", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Top Path 2", obj_checks=8),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Island 2", obj_checks=5),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Ruin Staircase", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach End Path", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach End Path Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Volcano Start", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Checkpoint 3", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Special Ruin Before Volcano", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin After Big Special Ruin Before Volcano", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path After Big Special Ruin Before Volcano Start", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path After Big Special Ruin Before Volcano Loop", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Cave Before Volcano Entrance", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Cave Before Volcano After First Block", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Cave Before Volcano After Second Block", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room", obj_checks=6),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room Alcove", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Bonus Key 3", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room Cannon Speed", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room Cannon Power", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room Cannon Flying", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Top Room", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Bobsled Start", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Checkpoint 4", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Bobsled", obj_checks=6),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Loop After Second Bobsled", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Loop", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Loop", obj_checks=5),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Whale Blowhole", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Whale Island Top", obj_checks=6),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Goal", obj_checks=100)
]