
"""
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
"""

from ....constants.char_ability import *
from ....constants.stage import *
from ....constants.stage_objs import *
from ....rule_builder.functions_ability_char import *
from ....rule_builder.functions_enemies import *
from ....rule_builder.functions_stage_obj import *
from ....rule_builder.functions_tricks import *
from ....world_base import SonicHeroesWorldBase

from ....constants.triple_spring import *


TRIPLE_SPRINGS: list[TripleSpringData] = \
[
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="After Beginning Falling Ruins 5 Rings Triple Spring", region_name="Seaside Hill Dark After Beginning Falling Ruins", power=2, no_control_time=30, item=ItemReward.Rings5, link_id=0, scale=0, x=-0.0004, y=40, z=-1432, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Lower Path After Beginning Flower Patch 5 Rings Triple Spring", region_name="Seaside Hill Dark Lower Path After Beginning Flower Patch", power=3.4999986, no_control_time=70, item=ItemReward.Rings5, link_id=0, scale=0, x=-0.0004, y=160, z=-1932, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Eggmans Robots Bottom 5 Rings Triple Spring", region_name="Seaside Hill Dark Eggmans Robots Bottom", power=2, no_control_time=20, item=ItemReward.Rings5, link_id=0, scale=0, x=-415.4742, y=330, z=-6660.969, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Top Cliff Route With Hermit Crab 5 Rings Triple Spring", region_name="Seaside Hill Dark Top Cliff Route With Hermit Crab", power=1, no_control_time=0, item=ItemReward.Rings5, link_id=0, scale=0, x=-1697.694, y=520, z=-6389.736, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="First Ruin Between First and Second Island Left 5 Rings Triple Spring", region_name="Seaside Hill Dark First Ruin Between First and Second Island", power=2, no_control_time=20, item=ItemReward.Rings5, link_id=0, scale=0, x=-4585.006, y=73.5, z=-11394.73, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="First Ruin Between First and Second Island Right 5 Rings Triple Spring", region_name="Seaside Hill Dark First Ruin Between First and Second Island", power=2, no_control_time=20, item=ItemReward.Rings5, link_id=0, scale=0, x=-4525.006, y=73.5, z=-11394.73, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Second Island First 5 Rings Triple Spring", region_name="Seaside Hill Dark Second Island", power=2, no_control_time=10, item=ItemReward.Rings5, link_id=0, scale=0, x=-4534.092, y=21.7605, z=-12103.58, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Second Island Second 5 Rings Triple Spring", region_name="Seaside Hill Dark Second Island", power=2, no_control_time=20, item=ItemReward.Rings5, link_id=0, scale=0, x=-4508.843, y=-4.9, z=-12752.63, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Ruin After First Bobsled 5 Rings Triple Spring", region_name="Seaside Hill Dark Ruin After First Bobsled", power=3.5000005, no_control_time=20, item=ItemReward.Rings5, link_id=0, scale=0, x=-1577.504, y=29.99, z=-16150.56, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Path Before Big Loop 5 Rings Triple Spring", region_name="Seaside Hill Dark Path Before Big Loop", power=5, no_control_time=20, item=ItemReward.Rings5, link_id=0, scale=0, x=-1720.006, y=350, z=-42013.09, rule=can_break_things_rule(team=Team.DARK, stage=Stage.SEASIDE_HILL) & has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING)),
    TripleSpringData(team=Team.DARK, stage=Stage.SEASIDE_HILL, location_name="Big Loop 5 Rings Triple Spring", region_name="Seaside Hill Dark Big Loop", power=10, no_control_time=40, item=ItemReward.Rings5, link_id=0, scale=0, x=2052.116, y=10, z=-43083.47, rule=has_stage_obj_rule(team=Team.DARK, stage_obj=StageObj.TRIPLE_SPRING))
]