"""
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
"""

from types import ModuleType
from ..constants.stage import Stage
from . import SeasideHill, OceanPalace#, GrandMetropolis, PowerPlant, CasinoPark, BingoHighway, RailCanyon, BulletStation, FrogForest, LostJungle, HangCastle, MysticMansion, EggFleet, FinalFortress

parser_level_result_mapping: dict[Stage, ModuleType] = \
{
    Stage.SEASIDE_HILL: SeasideHill,
    Stage.OCEAN_PALACE: OceanPalace,
    # Stage.GRAND_METROPOLIS: GrandMetropolis,
    # Stage.POWER_PLANT: PowerPlant,
    # Stage.CASINO_PARK: CasinoPark,
    # Stage.BINGO_HIGHWAY: BingoHighway,
    # Stage.RAIL_CANYON: RailCanyon,
    # Stage.BULLET_STATION: BulletStation,
    # Stage.FROG_FOREST: FrogForest,
    # Stage.LOST_JUNGLE: LostJungle,
    # Stage.HANG_CASTLE: HangCastle,
    # Stage.MYSTIC_MANSION: MysticMansion,
    # Stage.EGG_FLEET: EggFleet,
    # Stage.FINAL_FORTRESS: FinalFortress
}







