"""
Constants used by the parser
"""
import regex

from rule_builder.rules import Rule

from ..constants.char_ability import Team
from ..constants.stage import Stage
from ..constants.stage_objs import StageObj
from ..rule_builder.sonic_heroes_rules import RULES
from ..world_base import SonicHeroesWorldBase


# RULES_NAME: str = "RULES"
# GET_FORMATION_CHAR_RULE: str = f"{RULES_NAME}.get_formation_character_rule"
# GET_STAGE_OBJ_RULE: str = f"{RULES_NAME}.get_stage_obj_rule"
# GET_TEAM_BLAST_RULE: str = f"{RULES_NAME}.get_team_blast_rule"
# GET_ABILITY_RULE: str = f"{RULES_NAME}.get_ability_rule"
#
#
# TEAM_REF_STR: str = "Team"
# FORMATION_REF_STR: str = "Formation"
# HAS_FORM_CHAR_FOR_TEAM_DICT_NAME: str = "HAS_FORMATION_CHAR_RULES"
#
# ABILITY_REF_STR: str = "Ability"
# ABILITY_DICT_NAME: str = "CHAR_ABILITY_RULES"
#
# STAGE_OBJ_REF_STR: str = "StageObj"
# STAGE_OBJ_RULE_DICT_NAME: str = "STAGE_OBJ_RULES"


AND_CONDITION_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"(AND)")
OR_CONDITION_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"(OR)")
OUTER_PARENS_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"\((?>[^()]|(?R))*\)")

TEAM_HEADER: str = "Team"
LEVEL_HEADER: str = "Level"
SOURCE_HEADER: str = "Source"
TARGET_HEADER: str = "Target"
RULE_HEADER: str = "Rule"
NOTES_HEADER: str = "Notes"
NOTES_2_HEADER: str = "Notes 2"

NAME_HEADER: str = "Name"
OBJ_CHECKS_HEADER: str = "ObjChecks"

REGION_HEADER: str = "Region"
VOICE_LINE_HEADER: str = "Voiceline"
X_HEADER: str = "X"
Y_HEADER: str = "Y"
Z_HEADER: str = "Z"


PARSER_DOCSTRING_MSG: str = \
"""\"\"\"
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
\"\"\"
"""

PARSER_CHAR_ABILITY_IMPORT: str = "from ....constants.char_ability import *"
PARSER_STAGE_IMPORT: str = "from ....constants.stage import *"
PARSER_STAGE_OBJ_IMPORT: str = "from ....constants.stage_objs import *"
PARSER_CHAR_ABILITY_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_ability_char import *"
PARSER_ENEMIES_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_enemies import *"
PARSER_STAGE_OBJ_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_stage_obj import *"
PARSER_TRICKS_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_tricks import *"

PARSER_WORLD_BASE_IMPORT: str = "from ....world_base import SonicHeroesWorldBase"
PARSER_REGION_DATA_IMPORT: str = "from ....constants.loc_region import SonicHeroesRegionData"
PARSER_CONNECTION_DATA_IMPORT: str = "from ....constants.loc_region import SonicHeroesConnectionData"
PARSER_HINT_RING_IMPORT: str = "from ....constants.hint_rings import HintRingData"


PARSER_FILE_HEADER_START: str = \
f"""{PARSER_DOCSTRING_MSG}
{PARSER_CHAR_ABILITY_IMPORT}
{PARSER_STAGE_IMPORT}
{PARSER_STAGE_OBJ_IMPORT}
{PARSER_CHAR_ABILITY_FUNCTIONS_IMPORT}
{PARSER_ENEMIES_FUNCTIONS_IMPORT}
{PARSER_STAGE_OBJ_FUNCTIONS_IMPORT}
{PARSER_TRICKS_FUNCTIONS_IMPORT}
{PARSER_WORLD_BASE_IMPORT}
"""


REGION_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_REGION_DATA_IMPORT}

"""


CONNECTION_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_CONNECTION_DATA_IMPORT}

"""

HINT_RING_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_HINT_RING_IMPORT}

"""
