"""
Constants used by the parser
"""
import regex


AND_CONDITION_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"(AND)")
OR_CONDITION_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"(OR)")
OUTER_PARENS_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"\((?>[^()]|(?R))*\)")


SOURCE_HEADER: str = "Source"
TARGET_HEADER: str = "Target"

OBJ_CHECKS_HEADER: str = "ObjChecks"



TEAM_HEADER: str = "Team"
LEVEL_HEADER: str = "Level"
REGION_HEADER: str = "Region"
NAME_HEADER: str = "Name"
STAGE_OBJ_HEADER: str = "StageObj"
RULE_HEADER: str = "Rule"
LINK_ID_HEADER: str = "LinkID"
X_HEADER: str = "X"
Y_HEADER: str = "Y"
Z_HEADER: str = "Z"
NOTES_HEADER: str = "Notes"
NOTES_2_HEADER: str = "Notes 2"

SINGLE_SPRING_POWER_HEADER: str = "Single Spring Power"
SINGLE_SPRING_NO_CONTROL_TIME_HEADER: str = "Single Spring NoControlTime"

TRIPLE_SPRING_POWER_HEADER: str = "Triple Spring Power"
TRIPLE_SPRING_SCALE_HEADER: str = "Triple Spring Scale"
TRIPLE_SPRING_NO_CONTROL_TIME_HEADER: str = "Triple Spring NoControlTime"
TRIPLE_SPRING_ITEM_HEADER: str = "Triple Spring Item"

RING_TYPE_HEADER: str = "Ring Type"
RING_NUM_RINGS_HEADER: str = "Ring NumRings"
RING_LENGTH_HEADER: str = "Ring Length"
RING_RADIUS_HEADER: str = "Ring Radius"
RING_ID_OFFSET_HEADER: str = "Ring IDOffset"

HINT_RING_VOICELINE_HEADER: str = "Hint Ring Voiceline"

ITEM_BOX_ITEM_HEADER: str = "Item Box Item"

ITEM_BALLOON_ITEM_HEADER: str = "Item Balloon Item"



EGG_FLAPPER_WEAPON_HEADER: str = "Egg Flapper Weapon"
EGG_FLAPPER_ARMOR_HEADER: str = "Egg Flapper Armor"
EGG_FLAPPER_HEIGHT_HEADER: str = "Egg Flapper Height"

EGG_PAWN_SPECIAL_TYPE_HEADER: str = "Egg Pawn Special Type"
EGG_PAWN_WEAPON_HEADER: str = "Egg Pawn Weapon"
EGG_PAWN_SHIELD_HEADER: str = "Egg Pawn Shield"
EGG_PAWN_HEIGHT_HEADER: str = "Egg Pawn Height"



PARSER_DOCSTRING_MSG: str = \
"""\"\"\"
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
\"\"\"
"""

PARSER_CHAR_ABILITY_IMPORT: str = "from ....constants.char_ability import *"
PARSER_STAGE_IMPORT: str = "from ....constants.stage import *"
PARSER_STAGE_OBJ_IMPORT: str = "from ....constants.stage_objs import *"
PARSER_CHAR_ABILITY_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_ability_char import *"
PARSER_ENEMIES_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_enemies import *"
PARSER_STAGE_OBJ_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_stage_obj import *"
PARSER_TRICKS_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_tricks import *"

PARSER_WORLD_BASE_IMPORT: str = "from ....world_base import SonicHeroesWorldBase"
PARSER_REGION_DATA_IMPORT: str = "from ....constants.loc_region import SonicHeroesRegionData"
PARSER_CONNECTION_DATA_IMPORT: str = "from ....constants.loc_region import SonicHeroesConnectionData"
PARSER_HINT_RING_IMPORT: str = "from ....constants.hint_rings import HintRingData"
PARSER_ITEM_BALLOON_BOX_IMPORT: str = "from ....constants.item_balloon_box import *"
PARSER_ENEMY_IMPORT: str = "from ....constants.enemies import *"
PARSER_RING_IMPORT: str = "from ....constants.rings import RingData, RingLayout"
PARSER_TRIPLE_SPRING_IMPORT: str = "from ....constants.triple_spring import *"


PARSER_FILE_HEADER_START: str = \
f"""{PARSER_DOCSTRING_MSG}
{PARSER_CHAR_ABILITY_IMPORT}
{PARSER_STAGE_IMPORT}
{PARSER_STAGE_OBJ_IMPORT}
{PARSER_CHAR_ABILITY_FUNCTIONS_IMPORT}
{PARSER_ENEMIES_FUNCTIONS_IMPORT}
{PARSER_STAGE_OBJ_FUNCTIONS_IMPORT}
{PARSER_TRICKS_FUNCTIONS_IMPORT}
{PARSER_WORLD_BASE_IMPORT}
"""


REGION_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_REGION_DATA_IMPORT}

"""


CONNECTION_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_CONNECTION_DATA_IMPORT}

"""


HINT_RING_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_HINT_RING_IMPORT}

"""


ITEM_BALLOON_BOX_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_ITEM_BALLOON_BOX_IMPORT}

"""


ENEMY_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_ENEMY_IMPORT}

"""


RING_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_RING_IMPORT}

"""


TRIPLE_SPRING_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_TRIPLE_SPRING_IMPORT}

"""
