"""
Constants used by the parser
"""
import regex


AND_CONDITION_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"(AND)")
OR_CONDITION_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"(OR)")
OUTER_PARENS_PATTERN: regex.Pattern[str] = regex.compile(pattern=r"\((?>[^()]|(?R))*\)")

TEAM_HEADER: str = "Team"
LEVEL_HEADER: str = "Level"
SOURCE_HEADER: str = "Source"
TARGET_HEADER: str = "Target"
RULE_HEADER: str = "Rule"
NOTES_HEADER: str = "Notes"
NOTES_2_HEADER: str = "Notes 2"

NAME_HEADER: str = "Name"
OBJ_CHECKS_HEADER: str = "ObjChecks"

REGION_HEADER: str = "Region"
VOICE_LINE_HEADER: str = "Voiceline"
ITEM_HEADER: str = "Item"
X_HEADER: str = "X"
Y_HEADER: str = "Y"
Z_HEADER: str = "Z"


PARSER_DOCSTRING_MSG: str = \
"""\"\"\"
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
\"\"\"
"""

PARSER_CHAR_ABILITY_IMPORT: str = "from ....constants.char_ability import *"
PARSER_STAGE_IMPORT: str = "from ....constants.stage import *"
PARSER_STAGE_OBJ_IMPORT: str = "from ....constants.stage_objs import *"
PARSER_CHAR_ABILITY_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_ability_char import *"
PARSER_ENEMIES_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_enemies import *"
PARSER_STAGE_OBJ_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_stage_obj import *"
PARSER_TRICKS_FUNCTIONS_IMPORT: str = "from ....rule_builder.functions_tricks import *"

PARSER_WORLD_BASE_IMPORT: str = "from ....world_base import SonicHeroesWorldBase"
PARSER_REGION_DATA_IMPORT: str = "from ....constants.loc_region import SonicHeroesRegionData"
PARSER_CONNECTION_DATA_IMPORT: str = "from ....constants.loc_region import SonicHeroesConnectionData"
PARSER_HINT_RING_IMPORT: str = "from ....constants.hint_rings import HintRingData"
PARSER_ITEM_BALLOON_BOX_IMPORT: str = "from ....constants.item_balloon_box import *"


PARSER_FILE_HEADER_START: str = \
f"""{PARSER_DOCSTRING_MSG}
{PARSER_CHAR_ABILITY_IMPORT}
{PARSER_STAGE_IMPORT}
{PARSER_STAGE_OBJ_IMPORT}
{PARSER_CHAR_ABILITY_FUNCTIONS_IMPORT}
{PARSER_ENEMIES_FUNCTIONS_IMPORT}
{PARSER_STAGE_OBJ_FUNCTIONS_IMPORT}
{PARSER_TRICKS_FUNCTIONS_IMPORT}
{PARSER_WORLD_BASE_IMPORT}
"""


REGION_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_REGION_DATA_IMPORT}

"""


CONNECTION_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_CONNECTION_DATA_IMPORT}

"""


HINT_RING_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_HINT_RING_IMPORT}

"""


ITEM_BALLOON_BOX_PARSER_FILE_HEADER: str = \
f"""{PARSER_FILE_HEADER_START}
{PARSER_ITEM_BALLOON_BOX_IMPORT}

"""



