"""
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
"""

from types import ModuleType
from . import Sonic, Dark, Rose, Chaotix, SuperHardMode, AnyTeam
from ...constants.char_ability import Team

parser_team_result_mapping: dict[Team, ModuleType] = \
{
    Team.SONIC: Sonic,
    Team.DARK: Dark,
    Team.ROSE: Rose,
    Team.CHAOTIX: Chaotix,
    Team.SUPER_HARD_MODE: SuperHardMode,
    Team.ANY_TEAM: AnyTeam,
}

__all__ = ["parser_team_result_mapping"]
